dist: trusty
sudo: require

language: cpp

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
notifications:
  email:
    recipients:
      - gryzlov.ad@yandex.ru
    on_success: always
    on_failure: always
