dist: trusty
sudo: require

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
notifications:
  email:
    on_success: always
    on_failure: always
