dist: trusty
sudo: require

language: cpp

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
notifications:
  email:
    on_success: always
    on_failure: always
